apiVersion: apps/v1
kind: Deployment
metadata:
  name: $(deploymentId)
spec:
  selector:
    matchLabels:
      app: $(deploymentId)
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: $(deploymentId)
      annotations:
        git_commit: $(git_commit)
    spec:
      containers:
        - name: $(deploymentId)
          image: $(imageName)
          resources:
            requests:
              memory: $(memoryRequest)
            limits:
              memory: $(memoryLimit)
          ports:
            - containerPort: 8080
          env:
            - name: PROFILE_ARG
              value: $(profile)
            - name: DEPLOYMENT_ID
              value: $(deploymentId)
